import { PayloadAction, createSlice } from "@reduxjs/toolkit";
import { IData } from "../../type/type";

interface DataState {
  data: { [date: string]: number };
}

const initialState: DataState = {
  data: {},
};

export const contributionSlice = createSlice({
  name: "contribution",
  initialState,
  reducers: {
    getApiData(state, action: PayloadAction<IData>) {
      state.data = action.payload;
    },
  },
});

// Export action creators generated by Redux Toolkit
export const { getApiData } = contributionSlice.actions;

export default contributionSlice.reducer;
